[package]
name = "anysize"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A zero cost abstraction, adding types for data sizes"
repository = "https://github.com/rocco123q/anysize"
keywords = ["bit", "bits", "byte", "bytes"]
categories = ["data-structures", "development-tools", "embedded", "filesystem", "no-std"]

[dependencies]
concat-idents = "1.1.5"

[features]
default = ["default_sizes", "default_types"]
full = ["full_sizes", "full_types"]

# Sizes
u8 = []
u16 = []
u32 = []
u64 = []
u128 = []
usize = []

# Types
bits = []
bytes = []
hwords = []
words = []
dwords = []
qwords = []

default_sizes = ["u8", "u32", "usize"]
full_sizes = ["u8", "u16", "u32", "u64", "u128", "usize"]
default_types = ["bits", "bytes", "words"]
full_types = ["bits", "bytes", "hwords", "words", "dwords", "qwords"]
